services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-net

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - infra/.env
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/shoppingplanner?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./server/captures:/app/captures
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
